### ISSUE TITLE
Decouple `apollo-compiler` typed AST nodes from database

### ISSUE THREAD

**Issue by allancalix** [apollographql/apollo-rs#316]
## Description
The database interfaces are very useful and beneficial when performing repeated analysis on the same or similar documents. In the case of execution query validation, the indexing done by salsa adds some overhead to document parsing for a document that will only be analyzed once.

I implemented an AST visitor very much inspired by [async-graphql](https://github.com/async-graphql/async-graphql/blob/master/src/validation/visitor.rs#L19) but ended up duplicating the functions that map the untyped AST nodes to the typed ones used by the database. This works ok but it would be great to reuse the code already in the compiler.

One point where this gets a little tricky is with references to [parent types](https://sourcegraph.com/github.com/apollographql/apollo-rs@7b4cada6eb886b174bf8869aa967edc876417b0e/-/blob/crates/apollo-compiler/src/database/def.rs?L1039). Executable documents (i.e. queries) do not allow types to defined in the documents so these operations essentially always return none.

This decoupling would allow a user to get a typed AST without the database (useful for executable documents) as well as a typed AST with a database (for lookups against the schema.)

In practice, performing validation with the database indexing on the executable query vs directly with the typing transformation adds ~20% overhead to small queries but the cost is relatively fixed over a wide range of query sizes.

The basic flow I'm looking to satisfy is:
```mermaid
flowchart LR

SDL --> Schema(ApolloCompiler)
QueryString --> | ApolloParser| Query(Untyped Syntax Tree)
Query --> |Typed AST Transformation| TypedQuery(Typed Query AST)
Schema --> Visitor(AST Visitor)
TypedQuery --> Visitor
Visitor --> |Query type lookups| Schema
Visitor --> | Execution validation | Result(Validation Result)
```

**Comment by lrlna** [comment]
If I understand correctly, what you're looking for is being able to run the compiler on just an executable definition, rather than on both executable definition _and_ type system definition. Can you tell me a bit more about what you're trying to do? 

The visitor pattern doesn't work with apollo-compiler's design - it's a query-based compiler. They are usually considered to be separate compiler patterns. So I want to understand a bit better as to what your requirements are, and then seeing if we can think of a different way that works for this system.

I am currently doing a bit of an overhaul of the compiler to allow us to form a compile from multiple entries (#277). The primary use case for that is to be able to build out relationships from only the executable definitions and only the type system definitions, and then at some point combine the sources. Especially useful if you have multiple queries running against the same schema. There is, in fact, a lot rewriting happening to the way the HIRDatabase is created. I am aiming to entirely remove the typed AST manipulation and simply rely on pointers to access the correct AST data, which should also help with robustness of the system.

**Comment by allancalix** [comment]
What I want to do is validate many unique queries against a single schema. For that the compiler works perfectly to do lookups against the schema but I've had to replicate the typed AST factories starting from https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-compiler/src/database/def.rs#L323 for the sake of getting typed AST nodes.

I think a similar desire is being expressed in [this PR](https://github.com/apollographql/apollo-rs/pull/317#issuecomment-1262334469).

I'd be happy to explore an alternative pattern if you imagined a different approach to this, though overall I'm pretty happy with the outcome in terms of extensibility and performance.

**Comment by lrlna** [comment]
Since we've completely re-designed the compiler in the `1.0.0-beta.x` series, this issue is no longer applicable. I am closing it for the moment.
