### ISSUE TITLE
Wrong order of ignored tokens around types

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/apollo-rs#362]
Probably related to #325 but not identical?

### Steps to reproduce

```rust
use apollo_parser::Parser;
let  ast = Parser::new(r#"
type Query {
    field: Int # comment
}
"#.trim()).parse();
dbg!(ast.document());
```

### Expected result

We want a tree like:
- NAMED_TYPE
  - NAME (`Int`)
- WHITESPACE (` `)
- COMMENT (`# comment`)
- WHITESPACE (`\n`)

### Actual result

We get a tree like:
- NAMED_TYPE
  - COMMENT (`# comment`)
  - WHITESPACE (`\n`)
  - NAME (`Int`)

### Etc

I think this happens because the custom type parsing has this order of operations:
- Pop the token for the type (`Int`) into a local variable
   https://github.com/apollographql/apollo-rs/blob/d77e358819c320ad0e57ab21b9198f072ff18169/crates/apollo-parser/src/parser/grammar/ty.rs#L45
- Start the `NAMED_TYPE` node. This consumes ignored tokens, adding the comment and whitespace tokens to the parser AST
  https://github.com/apollographql/apollo-rs/blob/d77e358819c320ad0e57ab21b9198f072ff18169/crates/apollo-parser/src/parser/grammar/ty.rs#L161-L162
- Add the type token (`Int`) to the parser AST
  https://github.com/apollographql/apollo-rs/blob/d77e358819c320ad0e57ab21b9198f072ff18169/crates/apollo-parser/src/parser/grammar/ty.rs#L164

So trailing whitespace and comments get attached to the AST first. The spans are also wrong because of this.

Some potential fixes:
- the type parsing could use `.peek()` instead for the initial token and then `.pop()` at the right time
- maybe `.start_node()` should not eat ignored tokens, but force us to do it manually, to have more control over the order of tokens in the AST.

**Comment by lrlna** [comment]
ohhh this is _purely_ related to how different `ty.rs` does parsing, so it is, in fact, different to #325. I have previously considered to have `start_node()` to eat ignored tokens, but it adds a whole lot of overhead to all existing parsing rules? Perhaps worth it? Would be good to perhaps figure out how to do it accurately with just `peek()` and `pop()`.

**Comment by Freyert** [comment]
👋 I heard about this project on a podcast I believe, and it seemed like an interesting place to work on some of my interests (but weak points: rust, and everything in the compiler space).

I put the above case into  `crates/apollo-parser/test_data/parser/ok/0040_ignored_token_ordering_for_types.graphql`, ran `UPDATE_EXPECT=1 cargo test` in order to get the expected test output (even though it is incorrect). 

<details>
<summary> Full Expected Tree</summary>

```
- DOCUMENT@0..39
    - OBJECT_TYPE_DEFINITION@0..39
        - type_KW@0..4 "type"
        - WHITESPACE@4..5 " "
        - NAME@5..11
            - IDENT@5..10 "Query"
            - WHITESPACE@10..11 " "
        - FIELDS_DEFINITION@11..39
            - L_CURLY@11..12 "{"
            - WHITESPACE@12..17 "\n    "
            - FIELD_DEFINITION@17..38
                - NAME@17..22
                    - IDENT@17..22 "field"
                - COLON@22..23 ":"
                - WHITESPACE@23..24 " "
                - NAMED_TYPE@24..37
                    - COMMENT@24..33 "# comment"
                    - WHITESPACE@33..34 "\n"
                    - NAME@34..37
                        - IDENT@34..37 "Int"
                - WHITESPACE@37..38 " "
            - R_CURLY@38..39 "}"
recursion limit: 4096, high: 0
```
</details>


The area of concern looks like so:

```
  - NAMED_TYPE@24..37
      - COMMENT@24..33 "# comment"
      - WHITESPACE@33..34 "\n"
      - NAME@34..37 <-- should be first
          - IDENT@34..37 "Int"
```

I'm not familiar with the document format, but I'm inferring that `@24..33` indicates the position in the document where a token begins and ends?


Hope this is helpful! I would be really interested in helping in anyway I can, but I expect this might be an urgent issue that you all could close easily.
