### ISSUE TITLE
validation: apollo compiler validation ignore non existing fields

### ISSUE THREAD

**Issue by yanns** [apollographql/apollo-rs#392]
## Description

I'm trying to use apollo-compiler to validate queries against schema like in https://github.com/apollographql/router/issues/1116#issuecomment-1357342184

The validation does not fail on non-existing fields.

### Steps to reproduce

Considering the following:
```rust
        let input = indoc! {r#"
            type Review {
              id: Int!
            }

            type Query {
              reviews: [Review!]!
            }

            {
              reviews {
                id
                key
              }
            }
        "#};

        let ctx = ApolloCompiler::new(input);
        let diagnostics = ctx.validate();
        for diagnostic in &diagnostics {
            println!("{}", diagnostic);
        }
        assert!(diagnostics.is_empty());
```

### Expected result

`diagnostics` should not be empty.

### Actual result

`diagnostics` is empty.

### Environment

- `apollo-rs` crate: `apollo-compiler`
- Crate version: `0.4.1`

**Comment by lrlna** [comment]
@erikwrede would you like to make a PR to the compiler for this?

**Comment by erikwrede** [comment]
@lrlna sure! Might have some time to work on this next week.
I want to try out using rust's `traverse` crate first though because it uses a stack-based approach and evaluate if there's any benefits from eliminating recursion for longer/more nested queries. If not, I'll keep the recursive approach for now (which is what most of the reference implementations do). 

Would probably limit the scope to ObjectTypes without InlineFragments for now so we can evaluate the approach first.

**Comment by lrlna** [comment]
@erikwrede - no pressure at all! You've already put together a gist, I figured it would be good to merge that in :)

**Comment by erikwrede** [comment]
@lrlna pushed a draft to #441

**Comment by yanns** [comment]
Missing:
- https://github.com/apollographql/apollo-rs/issues/306
- https://github.com/apollographql/apollo-rs/issues/307

For the last one, https://github.com/apollographql/apollo-rs/pull/465

**Comment by lrlna** [comment]
this is now published as part of the new releases -- `cargo add apollo-compiler@0.7.1`.
