### ISSUE TITLE
Enable JSON (de)serialization for all AST nodes

### ISSUE THREAD

**Issue by networkimprov** [apollographql/apollo-rs#500]
Possibly related to #193

I'm building a GraphQL client app in Rust, which enables user-defined queries against any service. I'm using Tauri for the UI (HTML/CSS/JS rendered by a webview), hence I need to manifest an AST in Javascript. A JS parser would work, but I'd rather use the apollo-rs parser! But it doesn't seem to offer JSON de/serialization.

Could this be considered? Since the AST types are generated from the spec, would it be straightforward to implement?

**Comment by lrlna** [comment]
hi @networkimprov ! Ah interesting, that's a cool use case. Yes, this issue is quite similar to #193. At the moment that work is scheduled to go along with the implementation of execution part of graphql spec. The answer to whether or not this is straightforward is ... it depends. In best case scenario we can annotate with `#[derive(Serialize, Deserialize)]` on the AST structs we generate. In worst case scenario, those trait implementations will have to be manual. 

i'll close this issue in favour of #193, however, so let's keep discussing this there!
