### ISSUE TITLE
provide means to extend ApolloDiagnostic

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#606]
For those building on top of `apollo-compiler`, it'd be useful to be able to create additional `ApolloDiagnostic` on top of the existing graphql validation diagnostics. This allows to have a unified way of providing validation + extenral graphql diagnostics

**Comment by goto-bus-stop** [comment]
Something I thought about briefly was that maybe `DiagnosticData` could be a trait instead of an enum, so users would be able to add their own implementations. Then `ApolloDiagnostic` would contain a `Box<dyn DiagnosticData>`. Ifff we can do that without imposing too much implementation burden on users.

**Comment by lrlna** [comment]
yea trait will quite possibly work. we'll just want to provide docs and a couple of examples

**Comment by lrlna** [comment]
@goto-bus-stop i feel like we've done a work for this already. shall we close it?
