### ISSUE TITLE
feat(compiler): disallow anonymous operations

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/apollo-rs#625]
[This comment](https://github.com/apollographql/apollo-rs/blob/69311af67bfcd0ef36012f2a7f3221017190a6d3/crates/apollo-compiler/src/validation/operation.rs#L43-L47) explains that as soon as there is more than one operation in the compiler's context, anonymous operations are not allowed. 

I would love to be able to call `compiler.disallow_anonymous_operations()` to disallow _all_ anonymous operations when calling `compiler.validate()`.

**Comment by lrlna** [comment]
We gotta think about this one a bit. Because not allowing anonymous operations is not part of the specification, I wouldn't want to directly include it in compiler's validation process. I believe validation specifically in `compiler.validate()` should be spec-only. I see the point of being able to add extra validations specific to your business logic though.

**Comment by EverlastingBugstopper** [comment]
Yeah - it would be nice too to be able to re-use the diagnostics emitted for anonymous operations when there are more than one instead of trying to make my own. It's just such an edge case that we'd ever feed just one operation to the compiler, but unfortunately one I have to cover.

**Comment by goto-bus-stop** [comment]
The diagnostic in the compiler right now specifically calls out that you can only have anonymous operations if there's only one, so if we had a feature in the compiler to disallow anonymous operations, we'd want two different messages.

for this particular case it is possible to make your own diagnostic since everything is `pub`: 

https://github.com/apollographql/apollo-rs/blob/69311af67bfcd0ef36012f2a7f3221017190a6d3/crates/apollo-compiler/src/validation/operation.rs#L55-L57

but yeah you do need to implement your own check for it as well.

**Comment by EverlastingBugstopper** [comment]
that's good enough for me!
