### ISSUE TITLE
feat(compiler): disallow "unknown" operation types

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/apollo-rs#626]
Operation types are parsed as an enum of `Mutation | Query | Subscription | Other(unknown)`.

I would love to be able to call `compiler.disallow_unknown_operation_types()` that would emit diagnostics when calling `compiler.validate()` on a context that contains operations with unknown types.

**Comment by lrlna** [comment]
When creating the hir, we assume that if there isn't a operation type token, it's a query:

https://github.com/apollographql/apollo-rs/blob/69311af67bfcd0ef36012f2a7f3221017190a6d3/crates/apollo-compiler/src/database/hir_db.rs#L1312-L1327

The parser doesn't allow any other keyword other than `mutation`, `query` or `subscription`, and emits an error: 
https://github.com/apollographql/apollo-rs/blob/69311af67bfcd0ef36012f2a7f3221017190a6d3/crates/apollo-parser/src/parser/grammar/operation.rs#L77-L91

So I am not sure how you'd get to having an unknown operation type, other than having anonymous operations, which are in actuality queries. Did you run into an issue with an unknown operation type that isn't an anonymous operation? Otherwise, if it's only the anonymous operations that you'd like to disallow, then the other issue you opened is a good place to discuss that #625

**Comment by EverlastingBugstopper** [comment]
Oh... I got confused w/my internal `OperationType` (which has an `Other(string)` variant and the `OperationType` provided by the compiler - I just hadn't imported the one from `apollo-compiler` and so my autocomplete was leading me astray. Appreciate the help 😄
