### ISSUE TITLE
building a apollo_encoder Document from apollo_parser Document

### ISSUE THREAD

**Issue by yanns** [apollographql/apollo-rs#902]
We were using such code to build an `apollo_encoder` Document from an `apollo_parser` Document:
```rust
use apollo_parser::cst::Document;

fn derive_public_schema(doc: Document,...) {
    let mut pub_schema = apollo_encoder::Document::new();

    for definition in doc.definitions() {
        match definition {
            Definition::SchemaDefinition(e) => pub_schema.schema(e.try_into()?),
            Definition::OperationDefinition(e) => pub_schema.operation(e.try_into()?),
            Definition::FragmentDefinition(e) => pub_schema.fragment(e.try_into()?),
...
```

The update of `apollo_parser` to `0.8.x`. breaks this code.
I could not find how to deal with that. 
What would be the new way?

My goal is to transform the schema based on some custom directives and to compute its new SDL (as String)

**Comment by SimonSapin** [comment]
Despite it being in beta (… still, I really hope we can take care of that soon) apollo-compiler 1.0 has absorbed the functionality of apollo-encoder which is no longer in the repository.

1. Parse an `ast::Document` or a `Schema`, depending on which level of abstraction works best
2. Modify it as desired. When traversing a `Node<Example>` or `Component<Example>` shared-ownership pointer you'll likely need to call `.make_mut()` (which clones the value if it was shared, which it typically isn't after parsing) in order to get a `&mut Example`.
3. Serialize back to GraphQL syntax with the Display impl: either `doc.to_string()` or `println!("{doc}")` etc. To tweak the serialization config (currently, indentation), instead call `.serialize()` to get [something with builder methods](https://docs.rs/apollo-compiler/1.0.0-beta.20/apollo_compiler/ast/struct.Serialize.html) that also implement `Display` / `.to_string()`.

**Comment by yanns** [comment]
thanks a lot for the help!
I could rewrite the transformation with apollo-compiler.
The new API is much easier to use. The code is much better now. 
Thanks a lot for this!

**Comment by SimonSapin** [comment]
Glad to hear it went to well!
